### ISSUE TITLE
no .exe in zip download

### ISSUE THREAD

**Issue by reactor0138** [joetex/NXT-ucontrol#1]
HI Probably long shot as this is quite old but once I download the package there is no exe file. How do I download as an exe package to install on pc . cheers scott

**Comment by joetex** [comment]
You are in luck =).  I downloaded the code and built it in Visual Studio 2017, with zero issues!

I added a zip file to the code repo:
**NXTUControl-v1.0-build.zip**

This has 3 files:
**config.txt** - this is where the key binds are saved
**InTheHand.Net.Personal.dll** - this helps make the bluetooth connection to NXT
**RoboticsChallenge.exe** - this is NXTUControl built into an executable file.  This was used in a Robotics Competition, hence the name.  

This was built for the old NXT Mindstorms from around 2010 to 2014, I'm not sure if it will still work on modern NXTs because the bluetooth message format may have changed.

Good luck, let me know if it works to close this issue.
